import connectlogo from "@/assets/images/connect2.jpg";
export default {
  "parentUser": {
    "name": "John Doe",
    "image": 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/zuck.jpeg',
    "marriageStatus": "Married",
    "state": "California",
    "district": "Los Angeles",
    "locationPreference": "Yes",
    "gender": "M",
    "ageRange": "35-45",
    "outsideAgeRange": "No",
    "education": "Bachelor's Degree",
    "occupation": "Engineer",
    "caste": "No",
    "religion": "Same",
    "animals": "Dogs",
    "languages": ["English", "Spanish"],
    "zodiac": "Leo",
    "personalityType": "Introvert",
    "alcohol": "No",
    "smoking": "No",
    "diet": "Non-Vegetarian",
    "sports": "Football",
    "travel": "Yes",
    "exercise": "Regularly",
    "subParents": [
      {  
        "id": "sub1",
        "name": "Jane Doe",
        "image": 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/elon.png',
        "marriageStatus": "Single",
        "state": "California",
        "district": "San Francisco",
        "locationPreference": "Yes",
        "gender": "F",
        "ageRange": "30-40",
        "outsideAgeRange": "Yes",
        "education": "Master's Degree",
        "occupation": "Doctor",
        "caste": "Same",
        "religion": "Same",
        "animals": "Cats",
        "languages": ["English", "French"],
        "zodiac": "Virgo",
        "personalityType": "Extrovert",
        "alcohol": "Occasionally",
        "smoking": "No",
        "diet": "Vegetarian",
        "sports": "Tennis",
        "travel": "No",
        "exercise": "Occasionally"
      },
      {
        "id": "sub2",
        "name": "Michael Smith",
        "image": 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/jeff.jpeg',
        "marriageStatus": "Divorced",
        "state": "Texas",
        "district": "Houston",
        "locationPreference": "No",
        "gender": "M",
        "ageRange": "40-50",
        "outsideAgeRange": "No",
        "education": "Bachelor's Degree",
        "occupation": "Teacher",
        "caste": "No",
        "religion": "No",
        "animals": "None",
        "languages": ["English"],
        "zodiac": "Scorpio",
        "personalityType": "Ambivert",
        "alcohol": "No",
        "smoking": "Yes",
        "diet": "Non-Vegetarian",
        "sports": "Basketball",
        "travel": "Yes",
        "exercise": "Regularly"
      }
    ],
    "children": [
      {
        "id": "child1",
        "name": "Emily Doe",
        "image": 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/elon.png',
        "gender": "F",
        "age": 10,
        "marriageStatus": "Unmarried",
        "education": "Elementary School",
        "animals": "Dogs",
        "languages": ["English"],
        "sports": "Soccer",
        "travel": "Yes",
        "exercise": "Regularly"
      },
      {
        "id": "child2",
        "name": "David Doe",
        "image": 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/avatars/jeff.jpeg',
        "gender": "M",
        "age": 8,
        "marriageStatus": "married",
        "education": "Elementary School",
        "animals": "None",
        "languages": ["English"],
        "sports": "Swimming",
        "travel": "No",
        "exercise": "Occasionally"
      }
    ]
  }
};
